# -*- coding: utf-8 -*-
"""BloodCell_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rLjAU5YfId1sYwAkDORfAwoZumkbF2gh
"""

!rm -rf /content/BCCD_Dataset
!git clone https://github.com/Shenggan/BCCD_Dataset.git

ls -R /content/BCCD_Dataset/

import os
import random
import shutil

# Define dataset paths
image_dir = "/content/BCCD_Dataset/BCCD/JPEGImages"
train_dir = "/content/BCCD_Dataset/images/train"
val_dir = "/content/BCCD_Dataset/images/val"

# Create directories if they don’t exist
os.makedirs(train_dir, exist_ok=True)
os.makedirs(val_dir, exist_ok=True)

# List all images
all_images = [f for f in os.listdir(image_dir) if f.endswith(".jpg")]

# Shuffle images and split (80% train, 20% val)
random.shuffle(all_images)
split_idx = int(0.8 * len(all_images))  # 80% for training

train_images = all_images[:split_idx]
val_images = all_images[split_idx:]

# Move images to respective folders
for img in train_images:
    shutil.move(os.path.join(image_dir, img), os.path.join(train_dir, img))

for img in val_images:
    shutil.move(os.path.join(image_dir, img), os.path.join(val_dir, img))

print(f"✅ Moved {len(train_images)} images to Train and {len(val_images)} images to Val")

ls -R /content/BCCD_Dataset/images/

import os
import xml.etree.ElementTree as ET

# Define class names
classes = {"WBC": 0, "RBC": 1, "Platelets": 2}

# Paths
xml_dir = "/content/BCCD_Dataset/BCCD/Annotations"
txt_train_dir = "/content/BCCD_Dataset/labels/train/"
txt_val_dir = "/content/BCCD_Dataset/labels/val/"

os.makedirs(txt_train_dir, exist_ok=True)
os.makedirs(txt_val_dir, exist_ok=True)

# Function to convert XML to YOLO format
def convert_voc_to_yolo(xml_file, txt_dir):
    tree = ET.parse(xml_file)
    root = tree.getroot()

    width = int(root.find("size/width").text)
    height = int(root.find("size/height").text)

    txt_filename = os.path.join(txt_dir, root.find("filename").text.replace(".jpg", ".txt"))
    with open(txt_filename, "w") as f:
        for obj in root.findall("object"):
            class_name = obj.find("name").text
            if class_name not in classes:
                continue
            class_id = classes[class_name]

            xmin = int(obj.find("bndbox/xmin").text)
            ymin = int(obj.find("bndbox/ymin").text)
            xmax = int(obj.find("bndbox/xmax").text)
            ymax = int(obj.find("bndbox/ymax").text)

            # Normalize values
            x_center = (xmin + xmax) / (2 * width)
            y_center = (ymin + ymax) / (2 * height)
            bbox_width = (xmax - xmin) / width
            bbox_height = (ymax - ymin) / height

            f.write(f"{class_id} {x_center:.6f} {y_center:.6f} {bbox_width:.6f} {bbox_height:.6f}\n")

# Convert XML files in Annotations/
for xml_file in os.listdir(xml_dir):
    if xml_file.endswith(".xml"):
        convert_voc_to_yolo(os.path.join(xml_dir, xml_file), txt_train_dir)

print("✅ XML annotations converted to YOLO TXT format!")

ls -R /content/BCCD_Dataset/labels/

# Define label paths
label_src = "/content/BCCD_Dataset/labels/train"
label_train = "/content/BCCD_Dataset/labels/train"
label_val = "/content/BCCD_Dataset/labels/val"

os.makedirs(label_train, exist_ok=True)
os.makedirs(label_val, exist_ok=True)

# Move corresponding labels
for img in val_images:
    label_file = img.replace(".jpg", ".txt")
    if os.path.exists(os.path.join(label_src, label_file)):
        shutil.move(os.path.join(label_src, label_file), os.path.join(label_val, label_file))

print("✅ Labels moved to train/val correctly")

from glob import glob

# Find images
train_images = glob("/content/BCCD_Dataset/images/train/*.jpg")
val_images = glob("/content/BCCD_Dataset/images/val/*.jpg")

print(f"Found {len(train_images)} training images.")
print(f"Found {len(val_images)} validation images.")

!pip install torch
!pip install ultralytics

import os
from ultralytics import YOLO
import shutil
from google.colab import drive
import torch

dataset_yaml = """
path: /content/BCCD_Dataset
train: /content/BCCD_Dataset/images/train
val: /content/BCCD_Dataset/images/val
nc: 3
names: ['WBC', 'RBC', 'Platelets']
"""
with open("/content/BCCD_Dataset/dataset.yaml", "w") as f:
    f.write(dataset_yaml)

# Load YOLOv10 model and train
model = YOLO("yolov10n.pt")  # Using YOLOv10 Nano for efficiency

model.train(
    data="/content/BCCD_Dataset/dataset.yaml",
    epochs=25,
    batch=16,
    imgsz=640,
    workers=2,
    device='cuda' if torch.cuda.is_available() else 'cpu'
)

from google.colab import files

# Download best model
files.download("/content/runs/detect/train/weights/best.pt")

!export LC_ALL=C.UTF-8
!export LANG=C.UTF-8
!pip install ultralytics

!pip install streamlit
print("Tunnel password for opening streamlit")
!npm install -g localtunnel
!wget -q -O - https://loca.lt/mytunnelpassword

!pip install ultralytics
!rm -rf ~/.localtunnel
!streamlit run obj_det1.py & npx localtunnel --port 8501